# version 0.0.1

types:
  - deploy

# Build teonet docker image and upload it to Docker HUB
build_teonet_image:
  type: deploy
  tags:
      - docker_image_build
  script:
    - docker build --no-cache -t gitlab.ksproject.org:5000/teonet/teonode:$CI_BUILD_TAG -f docker/Dockerfile .
    - docker push gitlab.ksproject.org:5000/teonet/teonode:$CI_BUILD_TAG
    # update latest
    - docker tag -f gitlab.ksproject.org:5000/teonet/teonode:$CI_BUILD_TAG gitlab.ksproject.org:5000/teonet/teonode:latest
    - docker push gitlab.ksproject.org:5000/teonet/teonode:latest
  only:
    - tags  

